### ISSUE TITLE
Couldn't store data in cache Error

### ISSUE THREAD

**Issue by ericuldall** [google/google-api-php-client#1035]
I'm getting the following error when trying to do BigQuery insertAll operations.

Couldn't store data in cache in /vendors/google/vendor/google-api-php-client/src/Google/Cache/Memcache.php on 131

```
#0 /vendors/google/vendor/google-api-php-client/src/Google/Auth/OAuth2.php(315): Google_Cache_Memcache->set('[key]', '{"access_token"...')
#1 /vendors/1/google/vendor/google-api-php-client/src/Google/Auth/OAuth2.php(233): Google_Auth_OAuth2->refreshTokenWithAssertion()
#2 /vendors/google/vendor/google-api-php-client/src/Google/Service/Resource.php(205): Google_Auth_OAuth2->sign(Object(Google_Http_Request))
#3 /vendors/google/vendor/google-api-php-client/src/Google/Service/Bigquery.php(790): Google_Service_Resource->call('insertAll', Array, 'Google_Service_...')
#4 /modules/metrics/classes/Metrics/Bigquery.php(200): Google_Service_Bigquery_Tabledata_Resource->insertAll('[project]...', 'email', '[table]', Object(Google_Service_Bigquery_TableDataInsertAllRequest))
#5 /modules/metrics/classes/Metrics/Service.php(357): Metrics_Bigquery->insert_row('[project]...', 'email', '[table]', Array)
#6 /app/classes/Controller/Email/Metrics.php(44): Metrics_Service::trackEmailEvent('bigquery', Array)
```

I'm not sure if this is preventing data from actually making it into big query or not. Is there any way to resolve this issue?

**Comment by michaelbausor** [comment]
We recommend you start using the BigQuery library here: https://github.com/GoogleCloudPlatform/google-cloud-php
