### ISSUE TITLE
Google Drive Upload - Last Chunk Fatal error: Uncaught exception 'Google_Service_Exception' with message 'Failed to parse Content-Range header.'

### ISSUE THREAD

**Issue by bazzhar70** [google/google-api-php-client#1227]
I am having problem with resumable upload. I am uploading a video to my drive. The last chunk size for my upload always produce "Fatal error: Uncaught exception 'Google_Service_Exception' with message 'Failed to parse Content-Range header."

Almost 99% of my upload is sent but every time the  upload is about to finish, the error always shows up. I have tried formats like .mp4 and .mkv file with different sizes; 800MB,1.5Gig,3Gig,4Gig but same thing happens.

I examine the Response Header and  noticed the server returns error code 400. The "[X-GUploader-UploadID]" header returns 2 element with the same value which I think is part of the resume URI.
Also, the "Range" and somewhat "md5" like content is missing for the last chunk upload. 

Please enlighten me.

Here is the upload code

`
$resumeUri = "https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable&upload_id=AEnB2Uqcn7Z4JGrdwP8PaivzBjLzlix5pzGZFLJaaRqaYD6vnWAufOTDw5Ptch8CymX3s_lgXH3aCWOdTKzeyFwstpjhZiDiO_c6HxTQA4EybFkQvv9tggw";

$file = new Google_Service_Drive_DriveFile();
$file->title = "Big File";
$file->setName($fname);
$file->setParents(array($parentFolder));

$chunkSizeBytes = 256*1024*20;

// Call the API with the media upload, defer so it doesn't immediately return.
$client->setDefer(true);
$request = $service->files->create($file);
// Create a media file upload to represent our upload process.
$media = new Google_Http_MediaFileUpload(
  $client,
  $request,
  $mtype,
  null,
  true,
  $chunkSizeBytes
);

$status = false;
$handle = fopen($filePath, "rb");

$chunckTotalSent = 0;
$fileSize = getFileSizePerl($filePath);
$media->setFileSize($fileSize);

$resChunkSize = $media->resume($resumeUri);
while (!$status && !feof($handle)) {
  if ($client->isAccessTokenExpiredInNSeconds(120)) {
      $credentialsPath = expandHomeDirectory(CREDENTIALS_PATH);
      print "/////////////////////////////////////////////////////////\n";
      print "[   REFRESH TOKEN USED TO FETCH ACCESS TOKEN  IN       ]\n";
      print "/////////////////////////////////////////////////////////\n";
      $rt = TOKEN_REFRESH;
      $client->fetchAccessTokenWithRefreshToken($rt);      
      // $client->fetchAccessTokenWithRefreshToken($client->getRefreshToken());      
      file_put_contents($credentialsPath, json_encode($client->getAccessToken()));
      $accessToken = $client->getAccessToken();
      $client->setAccessToken($accessToken);
  }//end else

  print "File name : ".$fname." - ".$mtype."\n";
  print "Before fread\n";
  $chunk = fread($handle, $chunkSizeBytes);
  print "Before next_chunk\n";
  $status = $media->nextChunk($chunk);
  print "After next_chunk\n";

  $chunckTotalSent += $chunkSizeBytes;
  $progressSize = $media->getProgress();
  $percentComplete = ((100/$fileSize)*$progressSize);
  $fileContent =  
  " %Completed Upload : ".$percentComplete." \n".
  " File size : ".$fileSize." \n".
  " File Path : ".$filePath." \n".
  " MIME Type : ".$mtype." \n".
  " File in Bytes Sent : $chunckTotalSent \n".
  " Progress ".$progressSize."\n".
  " HTTPResultCode ".$media->getHttpResultCode()."\n".
  " File Size Sent ".$chunckTotalSent."\n".
  " Resume URI ".$media->getResumeUri()."\n".
  " ============================================================\n\n";
  //file_put_contents($assocFilename, json_encode($fileContent));
  print $fileContent;
 }

// The final value of $status will be the data from the API for the object
// that has been uploaded.
$result = false;
if($status != false) {
  $result = $status;
}

fclose($handle);
// Reset to the client to execute requests immediately in the future.
$client->setDefer(false);

PS.
 $client->isAccessTokenExpiredInNSeconds($seconds) is the custom method I made. No other custom
methods aside from that.
`

**Comment by prtk418** [comment]
i am also facing same issue:


`PHP Fatal error:  Uncaught exception 'Google_Service_Exception' with message 'Failed to parse Content-Range header.' in vendor/google/apiclient/src/Google/Http/REST.php:118

Stack trace:
#0 vendor/google/apiclient/src/Google/Http/REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), NULL)
#1 [internal function]: Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), NULL)
#2 vendor/google/apiclient/src/Google/Task/Runner.php(176): call_user_func_array(Array, Array)
#3 vendor/google/apiclient/src/Google/Http/REST.php(58): Google_Task_Runner->run()
#4 vendor/google/apiclient/src/Google/Client.php(788): Google_Http_R in /var/www/html/website-redesign/application/libraries/hla_app_log/vendor/google/apiclient/src/Google/Http/REST.php on line 118
`

**Comment by kocoten1992** [comment]
In my case, I was upload a directory :face_with_head_bandage: , something like this:

```
$gdrive->resumableUpload('/home/myuser/Downloads');
```

**Comment by levieraf** [comment]
@kocoten1992 and how did you fix it? I mean how did you resolve upload the document in the end?

**Comment by kocoten1992** [comment]
it was thank to you @levieraf , my code is similar to your, and you said it work, so I take a step back and realize my mistake.
The error message was no helping though.

**Comment by levieraf** [comment]
@kocoten1992 ohhh nice! well, remember to bring me a coffee xD!

**Comment by duvanvargas** [comment]
Im having the same issue

**Comment by pattoM** [comment]
Got here from a different google product (storage, python to the json api) but the api is pretty much same. My error was resolved by not declaring the total size of the file being uploaded i.e Content-Range: bytes 0-148576/*
