### ISSUE TITLE
The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by korpa** [google/google-api-php-client#1337]
I can get the information about the file: 

```
$optParams = [];
$response = $service->reports_files->get($profileId, $reportId, $fileId, $optParams);
```

But if I want to download the file, this does not work:
```
$optParams['alt'] = 'media';
$response = $service->reports_files->get($profileId, $reportId, $fileId, $optParams);
```

In this case I get following error:
```
Uncaught Google_Service_Exception: <?xml version='1.0' encoding='UTF-8'?><Error><Code>S
ignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your Google secret
key and signing method.</Message><StringToSign>GET

application/json
1510219436
/XXX/YYY.csv</StringToSign></Error> in /vagrant/vendo
r/google/apiclient/src/Google/Http/REST.php:118
Stack trace:
#0 /vagrant/vendor/google/apiclient/src/Google/Http/REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Obj
ect(GuzzleHttp\Psr7\Request), NULL)
#1 /vagrant/vendor/google/apiclient/src/Google/Task/Runner.php(176): Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHtt
p\Psr7\Request), NULL)
#2 /vagrant/vendor/google/apiclient/src/Google/Http/REST.php(58): Google_Task_Runner->run()
#3 /vagrant/vendor/google/apiclient/src/Google/Client.php(788): Google_Http_REST::exe in /vagrant/vendor/google/apiclient/src/Google/Http/RE
ST.php on line 118
```

I use the latest libs
```
google/apiclient          v2.2.1 Client library for Google APIs
google/apiclient-services v0.33  Client library for Google APIs
google/auth               v1.1.0 Google Auth Library for PHP
```

**Comment by mattwhisenhunt** [comment]
First two things off the top of my head:
Can you create a working request in API Explorer: https://developers.google.com/apis-explorer/#search/dfareporting/dfareporting/v2.8/dfareporting.reports.files.get?

And in the included Google/Service/Dfareporting.php file is the servicePath the latest version:
```php
$this->servicePath = 'dfareporting/v2.8/;'
```

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
