### ISSUE TITLE
Hello I'm having another problem exception 'Google_Service_Exception'

### ISSUE THREAD

**Issue by JonatanM** [google/google-api-php-client#511]
Hello I'm having another problem :( when I send the products to the google shopping

2015-03-21T03:55:47+00:00 ERR (3): 
exception 'Google_Service_Exception' with message 'Error calling POST https://www.googleapis.com/content/v2/100508066/products: (400) Unknown field name: adwords_labels' in /var/ROOT.com/vendor/google/apiclient/src/Google/Http/REST.php:83
Stack trace:
#0 /var/ROOT.com/vendor/google/apiclient/src/Google/Http/REST.php(41): Google_Http_REST::decodeHttpResponse(Object(Google_Http_Request), Object(Google_Client))
#1 /var/ROOT.com/vendor/google/apiclient/src/Google/Client.php(564): Google_Http_REST::execute(Object(Google_Client), Object(Google_Http_Request))
#2 /var/ROOT.com/vendor/google/apiclient/src/Google/Service/Resource.php(227): Google_Client->execute(Object(Google_Http_Request))
#3 /var/ROOT.com/vendor/google/apiclient/src/Google/Service/ShoppingContent.php(1014): Google_Service_Resource->call('insert', Array, 'Google_Service_...')
#4 /var/ROOT.com/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/GoogleShopping.php(18

**Comment by JonatanM** [comment]
https://github.com/bluevisiontec/GoogleShoppingApi/issues/24#issuecomment-85539228
