### ISSUE TITLE
PHP7 CredentialsLoader::makeCredentials() argument 2 wrong instance

### ISSUE THREAD

**Issue by MrGekko** [google/google-api-php-client#776]
I am getting this error with 2.0.0@rc2 But I have no idea what the error means... I have installed it with json and I am using a service account json file. 
```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Google\Auth\CredentialsLoader::makeCredentials() must be an instance of Psr\Http\Message\StreamInterface, instance of GuzzleHttp\Stream\Stream given, called in vendor/google/apiclient/src/Google/Client.php on line 1072 and defined in vendor/google/auth/src/CredentialsLoader.php:120
Stack trace:
#0 vendor/google/apiclient/src/Google/Client.php(1072): Google\Auth\CredentialsLoader::makeCredentials('https://www.goo...', Object(GuzzleHttp\Stream\Stream))
#1 vendor/google/apiclient/src/Google/Client.php(344): Google_Client->createApplicationDefaultCredentials(Object(GuzzleHttp\Client))
#2 vendor/google/apiclient/src/Google/Service/Resource.php(192): Google_Client->authorize(Object(GuzzleHttp\Client))
#3 vendor/google/apiclient/src/Google/Service/ShoppingContent.php(1967): Google_Service_Resource-> in vendor/google/auth/src/CredentialsLoader.php on line 120
```

Code used:

```
$client = new Google_Client();
$client->setAuthConfig('auth.json');
$client->setApplicationName(self::APPNAME);
$client->setClientId('123');
$client->setScopes('https://www.googleapis.com/auth/content');
```

* This might be a php7 issue *

**Comment by bshaffer** [comment]
Try pulling down the latest version (`RC4`) and this problem will be fixed.
